mutation AlertsConditionUpdate(
  $accountId: Int!, 
  $id: ID!,
  $name: String!,
  $enabled: Boolean!,
  $expirationInput:AlertsNrqlConditionExpirationInput,
  $nrqlInput:AlertsNrqlConditionUpdateQueryInput!,
  $signalInput:AlertsNrqlConditionSignalInput,
  $termsInput: [AlertsNrqlConditionTermsInput!]!,
  $description: String,
  $runbookUrl: String,
  $violationTimeLimitSeconds: Seconds
  
) {
  alertsNrqlConditionStaticUpdate(
    accountId: $accountId, 
    id: $id,
    condition: {
    name: $name,
    enabled: $enabled,
    nrql: $nrqlInput,
    terms: $termsInput,
    signal: $signalInput,
    expiration: $expirationInput,
    violationTimeLimitSeconds: $violationTimeLimitSeconds,
    description:$description,
    runbookUrl: $runbookUrl
    }
  ) {
    id
    description
    enabled
    expiration {
      closeViolationsOnExpiration
      expirationDuration
      openViolationOnExpiration
    }
    name
    nrql {
      query
    }
    runbookUrl
    signal {
      aggregationDelay
      aggregationMethod
      aggregationTimer
      aggregationWindow
      fillOption
      fillValue
      slideBy
    }
    terms {
      thresholdOccurrences
      thresholdDuration
      threshold
      priority
      operator
    }
    type
    violationTimeLimitSeconds
  }
}
