mutation NotificationChannelCreate(
  $accountId: Int!, 
  $notificationChannelInput: AlertsNotificationChannelCreateConfiguration!, 
  ) {
  alertsNotificationChannelCreate(
    accountId: $accountId, 
    notificationChannel: $notificationChannelInput) {
    error {
      errorType
      description
    }
    notificationChannel {
      ... on AlertsXMattersNotificationChannel {
        id
        name
      }
      ... on AlertsWebhookNotificationChannel {
        id
        name
      }
      ... on AlertsVictorOpsNotificationChannel {
        id
        name
      }
      ... on AlertsSlackNotificationChannel {
        id
        name
      }
      ... on AlertsPagerDutyNotificationChannel {
        id
        name
      }
      ... on AlertsOpsGenieNotificationChannel {
        id
        name
      }
      ... on AlertsNotificationChannel {
        id
        name
      }
      ... on AlertsEmailNotificationChannel {
        id
        name
      }
    }
  }
}
