mutation NotificationChannelDelete(
  $accountId: Int!,
  $id: ID!
){
  alertsNotificationChannelDelete(
    accountId: $accountId, 
    id: $id
  )
  {
    error {
      description
      errorType
      notificationChannelId
    }
    id
  }
}
